add metadata tab in settings
vue-polkadot/apps pull request #122
Opened 2020-08-07 04:49 UTC by yacare555

It adds the metadata tab in settings.
Regarding the detection of the right explorer in subscan, I think it's because of an inconsistency between the setting options (see picture).
<img width="536" alt="settings" src="https://user-images.githubusercontent.com/67239493/89609928-9b6f4c80-d84f-11ea-8266-b05bada46981.png">

2020-08-07 10:06 UTC, yangwao commented
Metatab looks good, but explorer detection is wrong. Leading link while on Edgeware goes to Kusama. See pic
<img width="1021" alt="Screenshot 2020-08-07 at 12 03 16" src="https://user-images.githubusercontent.com/5887929/89634882-65a98280-d8a6-11ea-9338-a479ab782092.png">

2020-08-07 11:46 UTC, yangwao approved these changes
While on Edgeware, link from explorer goes to Kusama.

2020-08-07 11:48 UTC, yangwao requested changes
While I'm on Edgeware, links lead to Kusama subscan

2020-08-10 04:17 UTC, yacare555 commented
Hi @yangwao, yes, maybe I have not expressed well, I think that's because you have Kusama selected as default explorer chain, (please see the last field in the pic I've posted before, and see the method  getExplorerUrl(value: string) in the component Card, ViewTransaction, etc, are all using the value of "default explorer chain" to create the url).
That's why I think there is an inconsistency in the UI because you can select an Edgeware nodeUrl and a Kusama default explorer chain at the same time.

2020-08-17 15:33 UTC, yangwao commented
Ok, it's in https://github.com/vue-polkadot/apps/pull/123

2020-08-17 15:33 UTC, merged